### ISSUE TITLE
FF60, Can't disable?

### ISSUE THREAD

**Issue by bkosborne** [BrianGilbert/xdebug-helper-for-firefox#10]
I'm experiencing a strange issue where I cannot turn the helper off. Normally I just click the icon and and select "Disable". This is indeed deleting the cookie (at least that's what FF dev toolbar tells me), but when I refresh the page, the cookie is sent to the server still!

Any idea what could be causing this? I don't have this issue in Chrome.

**Comment by binodkalathil** [comment]
Same behavior in Windows 10, FF 60.0.1

**Comment by BrianGilbert** [comment]
I'm using Nightlies and having no issued enabling and disabling.. this may be a windows specific issue?

**Comment by bkosborne** [comment]
I think this has been resolved, I haven't experienced this lately on my Mac

**Comment by binodkalathil** [comment]
Right, not on Windows also. This can be closed.

**Comment by BrianGilbert** [comment]
Thanks for confirmation @binodkalathil

**Comment by robme** [comment]
I am still experiencing this. It even turns itself back on in private windows. Even if I manually delete the cookie myself, it keeps re-enabling itself.

The icon is also buggy, especially in private windows. It shows as lit green, but when you click on it, the debugger is not enabled, or vice versa.
